###Router de cadastro
POST http://localhost:8000/api/register/
Content-Type: "application/json"

{
    "name": "Rai56",
    "email": "rai56@lkasjdkl",
    "telephone": "8978546549",
    "type": "driver",
    "password": "klçjlkjlk",
    "carbrand": "çljklçj",
    "carmodel": "lkjlk",
    "caryear": "698577",
    "carplate": "hkj68786"
}

### Listar usuários
GET http://localhost:8000/api/users/

### Listar usuário
GET http://localhost:8000/api/users/2